### ISSUE TITLE
arrow functionality for example in readme

### ISSUE THREAD

**Issue by secondl1ght** [bryanmylee/svelte-popperjs#18]
Hello 👋🏼 

Thanks for the great package, I am using the provided code example from the README here: https://github.com/bryanmylee/svelte-popperjs#example.

The tooltip is working but there is no arrow, are there any extra steps you need to make to get the arrow working? If so it would be good to include these in the same section.

**Comment by bryanmylee** [comment]
The example is simply re-implementing the standard tutorial. If the arrow isn't showing up, chances are you didn't style the components properly.

Refer to [this](https://popper.js.org/docs/v2/tutorial/), more specifically the code example here:

```css
#arrow,
#arrow::before {
  position: absolute;
  width: 8px;
  height: 8px;
  background: inherit;
}

#arrow {
  visibility: hidden;
}

#arrow::before {
  visibility: visible;
  content: '';
  transform: rotate(45deg);
}

#tooltip[data-popper-placement^='top'] > #arrow {
  bottom: -4px;
}

#tooltip[data-popper-placement^='bottom'] > #arrow {
  top: -4px;
}

#tooltip[data-popper-placement^='left'] > #arrow {
  right: -4px;
}

#tooltip[data-popper-placement^='right'] > #arrow {
  left: -4px;
}
```
